server:
  port: 8080
  servlet:
    context-path: /book

spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC   

     
logging:
  level:
    com.example.demo:  debug